### PR TITLE
Set SameSite=Lax for the cookie to fix remote debugging after redirects like in OAuth flow

### LINKED ISSUE #23: Doesn't work on redirect
If a site redirects to a location that has been configured to use the debugger, the debugger does not actually activate. For example, when debugging an OAuth flow, when the third party site redirects back to my local debugged site, the redirect back is never debugged.

### PR DESCRIPTION
**Pull request by Seros**
Fixes #23 and maybe #25 as well
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#values

### CODE REVIEW

**Review by Bilge — APPROVED** [review]

**Comment by Bilge** [comment]
@BrianGilbert How about a release for this?

**Comment by JeRoNZ** [comment]
@BrianGilbert Setting SameSite = lax would be of great use for debugging when returning from an external site, e.g. a card payment gateway (which I had to do yesterday). Any chance of a release to implement this?

**Comment by BrianGilbert** [comment]
thanks !

**Comment by Bilge** [comment]
How do I get this update? It seems my plugin is still setting `SameSite=Strict` ☹️

**Comment by Seros** [comment]
I guess the addon needs to be released and updated in Mozilla Addons @BrianGilbert ?

**Comment by hockdudu** [comment]
A new release has been made and released to Mozilla Addons (https://github.com/BrianGilbert/xdebug-helper-for-firefox/issues/35#issuecomment-1642908900).

**Pull request merged**
